[package]
name = "hypercore-protocol"
version = "0.1.0"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# simple-message-channels = "0.2.0"
simple-message-channels = { path = "../simple-message-channels" }
async-std = "1.5.0"
futures = "0.3.1"
snow = { git = "https://github.com/Frando/snow.git", branch = "datrs" }
prost = "0.6.1"
bytes = "0.5.4"
varinteger = "1.0.6"
rand = "0.7.3"
blake2-rfc = "0.2.18"
hex = "0.4.0"
async-trait = "0.1.22"
salsa20 = "0.4.0"
log = "0.4.8"
pretty-hash = "0.4.1"

[dev-dependencies]
env_logger = "0.7.1"

[build-dependencies]
prost-build = "0.6.1"
