[package]
name = "simple-hypercore-protocol"
version = "0.1.0"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-message-channels = "0.1.1"
async-std = "1.4.0"
futures = "0.3.1"
# snow = { path = "../snow" }
snow = { git = "https://github.com/Frando/snow.git", branch = "xchachapoly" }
prost = "0.6.1"
bytes = "0.5.4"
varinteger = "1.0.6"
rand = "0.7.3"

[build-dependencies]
prost-build = "0.6.1"
