[package]
name = "hypercore-protocol"
version = "0.0.1"
license = "MIT OR Apache-2.0"
description = "Binary replication protocol for Hypercore feeds"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
documentation = "https://docs.rs/hypercore-protocol"
repository = "https://github.com/Frando/hypercore-protocol-rs"
readme = "README.md"
edition = "2018"
keywords = ["dat", "p2p", "stream", "feed", "hypercore", "protocol"]
categories = [
  "asynchronous",
  "concurrency",
  "cryptography",
  "data-structures",
  "encoding",
]

[dependencies]
futures = "0.3"
snow = { git = "https://github.com/Frando/snow.git", branch = "datrs", features = ["risky-raw-split", "xchachapoly"] }
prost = "0.6"
bytes = "0.5"
varinteger = "1.0"
rand = "0.7"
blake2-rfc = "0.2"
hex = "0.4"
async-trait = "0.1"
salsa20 = "0.4"
log = "0.4"
pretty-hash = "0.4"
futures-timer = "3.0"
instant = "0.1"
getrandom = "0.1"
pin-project-lite = "0.1.4"

[dev-dependencies]
async-std = "1.5.0"
simple-message-channels = "0.2.0"
env_logger = "0.7.1"
hypercore = { git = "https://github.com/bltavares/hypercore", branch = "async-trait" }
# hypercore = { path = "../hypercore" }
random-access-disk = "2.0.0"
random-access-memory = "2.0.0"
random-access-storage = "4.0.0"

[build-dependencies]
prost-build = "0.6.1"

[features]
wasm-bindgen = [
  "instant/wasm-bindgen", 
  "getrandom/wasm-bindgen", 
  "futures-timer/wasm-bindgen"
]
