[package]
name = "hypercore-protocol"
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "Binary replication protocol for Hypercore feeds"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
documentation = "https://docs.rs/hypercore-protocol"
repository = "https://github.com/Frando/hypercore-protocol-rs"
readme = "README.md"
edition = "2018"
keywords = ["dat", "p2p", "stream", "feed", "hypercore", "protocol"]
categories = [
  "asynchronous",
  "concurrency",
  "cryptography",
  "data-structures",
  "encoding",
]

[dependencies]
async-std = "1.5.0"
simple-message-channels = "0.2.0"
futures = "0.3.1"
snow = { git = "https://github.com/Frando/snow.git", branch = "datrs-new", features = ["risky-raw-split", "xchachapoly"] }
prost = "0.6.1"
bytes = "0.5.4"
varinteger = "1.0.6"
rand = "0.7.3"
blake2-rfc = "0.2.18"
hex = "0.4.0"
async-trait = "0.1.22"
salsa20 = "0.4.0"
log = "0.4.8"
pretty-hash = "0.4.1"
futures-timer = "3.0.2"

[dev-dependencies]
env_logger = "0.7.1"
hypercore = { git = "https://github.com/bltavares/hypercore", branch = "bitfield-compress" }

[build-dependencies]
prost-build = "0.6.1"
